apiVersion: apps/v1
kind: Deployment
metadata:
  name: raid-time
  labels:
    app: raid-time
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: raid-time
  replicas: 1
  template:
    metadata:
      labels:
        app: raid-time
    spec:
      containers:
        - name: raid-time
          image: ghcr.io/rekyuu/raid-time:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: raid-time
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 8000
    port: 80
  selector:
    app: raid-time
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: raid-time
spec:
  routes:
    - kind: Rule
      match: Host(`raids.riichi.me`)
      priority: 10
      services:
        - name: raid-time
          port: 80
