services:
  minecraft:
    image: marctv/minecraft-papermc-server:1.20.6
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-data:/data
    environment:
      PUID: 1000
      PGID: 1000
    stdin_open: true
    tty: true
  caddy:
    image: caddy:2.8.4-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/services/caddy/caddy-data:/data
      - $HOME/services/caddy/caddy-config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile