apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumakaini-request-processor
  labels:
    app: kumakaini-request-processor
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kumakaini-request-processor
  replicas: 1
  template:
    metadata:
      labels:
        app: kumakaini-request-processor
    spec:
      containers:
        - name: kumakaini-request-processor
          image: ghcr.io/rekyuu/kumakaini-request-processor:3.0.0-beta.6
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: redis-password
            - name: DANBOORU_USER
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: danbooru-user
            - name: DANBOORU_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: danbooru-api-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: openai-api-key
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-host
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumakaini-discord
  labels:
    app: kumakaini-discord
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kumakaini-discord
  replicas: 1
  template:
    metadata:
      labels:
        app: kumakaini-discord
    spec:
      containers:
        - name: kumakaini-discord
          image: ghcr.io/rekyuu/kumakaini-discord:3.0.0-beta.6
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: redis-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-host
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-database
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: discord-token
            - name: DISCORD_MOD_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: discord-mod-role-id
            - name: DISCORD_ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: discord-admin-id
            - name: DISCORD_MOON_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: discord-moon-guild-id
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumakaini-telegram
  labels:
    app: kumakaini-telegram
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kumakaini-telegram
  replicas: 1
  template:
    metadata:
      labels:
        app: kumakaini-telegram
    spec:
      containers:
        - name: kumakaini-telegram
          image: ghcr.io/rekyuu/kumakaini-telegram:3.0.0-beta.6
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: redis-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-host
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: postgres-database
            - name: TELEGRAM_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: telegram-access-token
            - name: TELEGRAM_ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: kuma-secrets
                  key: telegram-admin-id