services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-data:/data
    environment:
      UID: 1000
      GID: 1000
      TYPE: FABRIC
      EULA: "TRUE"
      VERSION: "1.20.1"
      MAX_MEMORY: 8G
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS: |-
        cobblemon
        cobbledex
        cobbreeding
        create-fabric:beta
        dynmap:beta
        jei
        inventory-sorting
        simple-backup
        simple-death-chest
    stdin_open: true
    tty: true
  caddy:
    image: caddy:2.8.4-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/services/caddy/caddy-data:/data
      - $HOME/services/caddy/caddy-config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile