services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-data:/data
    environment:
      UID: 1000
      GID: 1000
      TYPE: FABRIC
      EULA: "TRUE"
      VERSION: "1.20.1"
      MAX_MEMORY: 8G
      MODRINTH_LOADER: fabric
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS: |-
        bellsandwhistles
        betterdays
        cobbled-shiny-particles
        cobblefoods
        cobblemon
        cobblemon-capture-xp
        cobblemon-fight-or-flight
        cobblemon-loot-balls
        cobblemon-pokedex
        cobblemon-pokenav
        cobblemon-unchained
        cobblemon-whiteout
        cobblemounts
        cobblepedia
        cobbreeding
        copycats
        corgilib
        create-big-cannons
        create-cobblemon-industrialized
        create-enchantment-industry-fabric
        create-fabric
        create-food
        create-goggles
        create-railways-navigator
        create-slugma
        dynmap
        enhanced-celestials
        fabric-seasons
        fabric-seasons-delight-compat
        fabric-seasons-extras
        farmers-delight-refabricated
        gravestones
        gravestones-fix
        immersive-snow
        inventory-sorting
        jade
        jei
        multiworld
        simple-backup
        slice-and-dice
        snow-real-magic
        waystones
    stdin_open: true
    tty: true
  caddy:
    image: caddy:2.8.4-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/services/caddy/caddy-data:/data
      - $HOME/services/caddy/caddy-config:/config
      - $HOME/services/caddy/Caddyfile:/etc/caddy/Caddyfile