services:
  psql:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres